import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import ranking from './unit/ranking.mjs';
import reviewFixes from './unit/review-fixes.mjs';
import capture from './unit/capture.mjs';
import classify from './unit/classify.mjs';
import summaries from './unit/summaries.mjs';
import snippet from './unit/snippet.mjs';
import render from './unit/render.mjs';
import vectors from './unit/vectors.mjs';
import relevance from './unit/relevance.mjs';
import install from './unit/install.mjs';
import update from './unit/update.mjs';
import seed from './unit/seed.mjs';
import usages from './unit/usages.mjs';
import usagesErrors from './unit/usages-errors.mjs';
import store from './unit/store.mjs';
import busyTimeout from './unit/busy-timeout.mjs';
import budget from './unit/budget.mjs';
import project from './unit/project.mjs';
import cursors from './unit/cursors.mjs';
import graph from './unit/graph.mjs';
import graphQuery from './unit/graph-query.mjs';
import progress from './unit/progress.mjs';
import refresh from './unit/refresh.mjs';
import adapters from './unit/adapters.mjs';
import shown from './unit/shown.mjs';
import injectDefaults from './unit/inject-defaults.mjs';
import promptRecall from './unit/prompt-recall.mjs';
import compact from './unit/compact.mjs';
import captureTurns from './unit/capture-turns.mjs';
import claudeCli from './unit/claude-cli.mjs';
import doctorClaude from './unit/doctor-claude.mjs';
import backfillOutput from './unit/backfill-output.mjs';
import skills from './unit/skills.mjs';
import catchup from './unit/catchup.mjs';
import projectKey from './unit/project-key.mjs';
import projectLinks from './unit/project-links.mjs';
import projectKeyRun from './unit/project-key-run.mjs';
import pick from './unit/pick.mjs';
import surface from './unit/surface.mjs';
import reingest from './unit/reingest.mjs';
import syncStatus from './unit/sync-status.mjs';
import factsOps from './unit/facts-ops.mjs';
import facts from './unit/facts.mjs';
import fixtures from './unit/fixtures.mjs';
import suggest from './unit/suggest.mjs';
import preferUsages from './unit/prefer-usages.mjs';
import stopwords from './unit/stopwords.mjs';
import scanVersion from './unit/scan-version.mjs';
import extract from './unit/extract.mjs';
import graphImports from './unit/graph-imports.mjs';
import graphAliases from './unit/graph-aliases.mjs';
import graphPython from './unit/graph-python.mjs';
import graphGo from './unit/graph-go.mjs';
import graphRust from './unit/graph-rust.mjs';
import graphJava from './unit/graph-java.mjs';
import graphKotlin from './unit/graph-kotlin.mjs';
import benchUsages from './unit/bench-usages.mjs';
import graphRefresh from './unit/graph-refresh.mjs';
import graphReceivers from './unit/graph-receivers.mjs';
import graphFixtures from './unit/graph-fixtures.mjs';
import grammars from './unit/grammars.mjs';
import graphAnswer from './unit/graph-answer.mjs';
import view from './unit/view.mjs';
import summarize from './unit/summarize.mjs';
import { report } from './lib/check.mjs';

const graphCache = mkdtempSync(join(tmpdir(), 'unit-graph-cache-'));
process.env.CLAUDE_DB_GRAPH_CACHE = graphCache;

await ranking();
await reviewFixes();
await suggest();
await stopwords();
await scanVersion();
await extract();
await graphImports();
await graphAliases();
await graphPython();
await graphGo();
await graphRust();
await graphJava();
await graphKotlin();
await benchUsages();
await graphRefresh();
await graphReceivers();
await graphFixtures();
await grammars();
await graphAnswer();
await view();
await summarize();
await preferUsages();
await capture();
await classify();
await summaries();
await snippet();
await render();
await vectors();
await relevance();
await install();
await update();
await seed();
await usages();
await usagesErrors();
await store();
await busyTimeout();
await budget();
await project();
await cursors();
await graph();
await graphQuery();
await progress();
await refresh();
await shown();
await injectDefaults();
await promptRecall();
await compact();
await captureTurns();
await claudeCli();
await doctorClaude();
await backfillOutput();
await skills();
await catchup();
await projectKey();
await projectLinks();
await projectKeyRun();
await pick();
await surface();
await reingest();
await syncStatus();
await factsOps();
await facts();
await fixtures();
await adapters();

rmSync(graphCache, { recursive: true, force: true });
report('unit');
