import ranking from './unit/ranking.mjs';
import capture from './unit/capture.mjs';
import classify from './unit/classify.mjs';
import summaries from './unit/summaries.mjs';
import snippet from './unit/snippet.mjs';
import render from './unit/render.mjs';
import vectors from './unit/vectors.mjs';
import relevance from './unit/relevance.mjs';
import install from './unit/install.mjs';
import update from './unit/update.mjs';
import seed from './unit/seed.mjs';
import usages from './unit/usages.mjs';
import usagesErrors from './unit/usages-errors.mjs';
import store from './unit/store.mjs';
import project from './unit/project.mjs';
import cursors from './unit/cursors.mjs';
import graph from './unit/graph.mjs';
import graphQuery from './unit/graph-query.mjs';
import progress from './unit/progress.mjs';
import refresh from './unit/refresh.mjs';
import adapters from './unit/adapters.mjs';
import shown from './unit/shown.mjs';
import injectDefaults from './unit/inject-defaults.mjs';
import suggest from './unit/suggest.mjs';
import preferUsages from './unit/prefer-usages.mjs';
import stopwords from './unit/stopwords.mjs';
import scanVersion from './unit/scan-version.mjs';
import { report } from './lib/check.mjs';

await ranking();
await suggest();
await stopwords();
await scanVersion();
await preferUsages();
await capture();
await classify();
await summaries();
await snippet();
await render();
await vectors();
await relevance();
await install();
await update();
await seed();
await usages();
await usagesErrors();
await store();
await project();
await cursors();
await graph();
await graphQuery();
await progress();
await refresh();
await shown();
await injectDefaults();
await adapters();

report('unit');
